version: 2

sources:
  - name: GENERATION_RAW
    database: ENERGY_RAW
    schema: GENERATION
    tables:
      - name: GENERATION_HISTORY

  - name: CAPACITY_RAW
    database: ENERGY_RAW
    schema: CAPACITY
    tables:
      - name: CAPACITY_HISTORY

  - name: CONSUMPTION_RAW
    database: ENERGY_RAW
    schema: CONSUMPTION
    tables:
      - name: CONSUMPTION_HISTORY

  - name: EMISSION_RAW
    database: ENERGY_RAW
    schema: EMISSION
    tables:
      - name: EMISSION_HISTORY