name: dbt CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          pip install dbt-snowflake sqlfluff sqlfluff-templater-dbt

      - name: Set environment variables
        run: |
          echo "DBT_PROFILES_DIR=." >> $GITHUB_ENV

      - name: Create profiles.yml
        run: |
          cat <<EOF > profiles.yml
          dbt_energy_analysis:
          target: ci
          outputs:
            ci:
              type: snowflake
              account: "${SNOWFLAKE_ACCOUNT}"
              user: "${SNOWFLAKE_USER}"
              password: "${SNOWFLAKE_PASSWORD}"
              role: "${SNOWFLAKE_ROLE}"
              database: "${SNOWFLAKE_DATABASE}"
              warehouse: "${SNOWFLAKE_WAREHOUSE}"
              schema: CI_${GITHUB_RUN_ID}
              threads: 4
          EOF

      - name: Run dbt debug
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: dbt debug

      - name: Run dbt build
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: dbt build --target ci
